# Generated by Django 2.2.19 on 2022-05-25 19:59

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_recipes_Ingredient_contrains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ярлык')),
                ('color', models.CharField(default='#3B0363', max_length=7, validators=[recipes.validators.validate_color], verbose_name='Цвет ярлыка')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[recipes.validators.validate_slug], verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Ярлык',
                'verbose_name_plural': 'Ярлыки',
            },
        ),
    ]
